-- Creates a denormalized table with MAP data for several years
SELECT a.*
INTO mapYears
FROM (
SELECT *
FROM dbo.F_GET_MAP(2012, DEFAULT)
UNION ALL
SELECT *
FROM dbo.F_GET_MAP(2013, DEFAULT)
UNION ALL
SELECT *
FROM dbo.F_GET_MAP(2014, DEFAULT)
UNION ALL
SELECT *
FROM dbo.F_GET_MAP(2017, DEFAULT)
UNION ALL
SELECT *
FROM dbo.F_GET_MAP(2016, DEFAULT)) AS a;

-- Creates a denormalized table with KPREP data for several years
SELECT a.*
INTO kprepYears
FROM (
SELECT *
FROM dbo.F_GET_KPREP(2012, DEFAULT)
UNION ALL
SELECT *
FROM dbo.F_GET_KPREP(2013, DEFAULT)
UNION ALL
SELECT *
FROM dbo.F_GET_KPREP(2014, DEFAULT)
UNION ALL
SELECT *
FROM dbo.F_GET_KPREP(2015, DEFAULT)
UNION ALL
SELECT *
FROM dbo.F_GET_KPREP(2016, DEFAULT)) AS a;

